[window.dimensions]
columns=65
lines=25
[window.padding]
x=0        # Remove or reduce horizontal padding
y=0        # Remove or reduce vertical padding
# dynamic_padding=false   # Disable dynamic padding
# [window.decorations]
# decorations="None"        # Remove window decorations (borders, etc.)


[window]
opacity=0.9             # Ensure full opacity (no transparency)

[font]
size=12

[font.normal]
family = "FiraCode Nerd Font"
style = "Regular"

# Colors (Gruvbox dark)
[colors.primary]
# hard contrast: background = '#1d2021'
background='#1d2021'
# soft contrast: background = '#32302f'
foreground='#ebdbb2'

  # Normal colors
[colors.normal]
black='#282828'
red='#cc241d'
green='#98971a'
yellow='#d79921'
blue='#458588'
magenta='#b16286'
cyan='#689d6a'
white='#a89984'

  # Bright colors
[colors.bright]
black='#928374'
red='#fb4934'
green='#b8bb26'
yellow='#fabd2f'
blue='#83a598'
magenta='#d3869b'
cyan='#8ec07c'
white='#ebdbb2'

# [cursor.style]
# shape="|"
# blinking="On"
# live_config_reload=true

